name: Pull Request Workflow

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name for deployment'
        required: true
        type: string
      pr_number:
        description: 'PR number for deployment'
        required: true
        type: string

permissions:
  contents: read
  deployments: write
  checks: write
  pull-requests: write

jobs:
  # Build and Deploy API
  build-api:
    uses: ./.github/workflows/template-build.yml
    with:
      build_type: 'api'
      environment: 'production'
      run_tests: true

  deploy-api:
    needs: build-api
    uses: ./.github/workflows/template-deploy.yml
    secrets: inherit
    with:
      deploy_type: 'api'
      environment: 'branch'
      branch_name: ${{ github.event.pull_request.head.ref || inputs.branch_name }}
      pr_number: ${{ github.event.pull_request.number || inputs.pr_number }}

  # Test API
  test-api:
    needs: deploy-api
    uses: ./.github/workflows/template-test.yml
    with:
      test_type: 'api'
      api_url: ${{ needs.deploy-api.outputs.api_deployment_url }}
      environment: 'branch'
      artifact_name_suffix: '-branch'

  # Security validation for API
  security-api:
    needs: deploy-api
    uses: ./.github/workflows/template-security.yml
    secrets: inherit
    with:
      check_type: 'gcp_validation'
      api_url: ${{ needs.deploy-api.outputs.api_deployment_url }}
      branch_name: ${{ github.event.pull_request.head.ref || inputs.branch_name }}

  # Build and Deploy Web (optional for branch deployments)
  build-web:
    needs: [deploy-api, test-api]
    if: needs.test-api.result == 'success'
    uses: ./.github/workflows/template-build.yml
    with:
      build_type: 'web'
      environment: 'production'
      api_url: ${{ needs.deploy-api.outputs.api_deployment_url }}
      run_tests: true

  deploy-web:
    needs: [build-web, deploy-api, test-api]
    if: needs.test-api.result == 'success'
    uses: ./.github/workflows/template-deploy.yml
    secrets: inherit
    with:
      deploy_type: 'web'
      environment: 'branch'
      api_url: ${{ needs.deploy-api.outputs.api_deployment_url }}
      branch_name: ${{ github.event.pull_request.head.ref || inputs.branch_name }}
      pr_number: ${{ github.event.pull_request.number || inputs.pr_number }}

  # Integration Tests
  test-integration:
    needs: [deploy-api, test-api, deploy-web]
    if: needs.deploy-web.result == 'success'
    uses: ./.github/workflows/template-test.yml
    with:
      test_type: 'integration'
      web_url: ${{ needs.deploy-web.outputs.web_deployment_url }}
      api_url: ${{ needs.deploy-api.outputs.api_deployment_url }}
      environment: 'branch'
      artifact_name_suffix: '-branch'

  # E2E Tests (optional for branch deployments)
  test-e2e:
    needs: [deploy-api, test-api, deploy-web, test-integration]
    if: needs.test-integration.result == 'success'
    uses: ./.github/workflows/template-test.yml
    with:
      test_type: 'e2e'
      web_url: ${{ needs.deploy-web.outputs.web_deployment_url }}
      api_url: ${{ needs.deploy-api.outputs.api_deployment_url }}
      environment: 'branch'
      artifact_name_suffix: '-branch'

  # Security validation for full deployment
  security-full:
    needs: [deploy-api, deploy-web]
    if: needs.deploy-web.result == 'success'
    uses: ./.github/workflows/template-security.yml
    secrets: inherit
    with:
      check_type: 'cors_test'
      api_url: ${{ needs.deploy-api.outputs.api_deployment_url }}
      web_url: ${{ needs.deploy-web.outputs.web_deployment_url }}

  # Deployment Summary
  deployment-summary:
    needs: [deploy-api, test-api, deploy-web, test-integration, test-e2e, security-api, security-full]
    if: always()
    uses: ./.github/workflows/template-release.yml
    with:
      release_type: 'deployment_summary'
      environment: 'branch'
      api_url: ${{ needs.deploy-api.outputs.api_deployment_url }}
      web_url: ${{ needs.deploy-web.outputs.web_deployment_url }}
      api_deployment_status: ${{ needs.deploy-api.result }}
      web_deployment_status: ${{ needs.deploy-web.result }}
      api_test_status: ${{ needs.test-api.result }}
      integration_test_status: ${{ needs.test-integration.result }}
      e2e_test_status: ${{ needs.test-e2e.result }}
      branch_name: ${{ github.event.pull_request.head.ref || inputs.branch_name }}
      pr_number: ${{ github.event.pull_request.number || inputs.pr_number }}